= EleanorLordPray: человек и проект
gk11.ru
:lang: ru
:date: 2017-11-25


****
Элеонора не была ни знаменитостью, ни великой писательницей. Просто писала письма. Немножко баловалась фотографией. И создала самую потрясающую хронику одного небольшого русского города - 16 тысяч страниц. День за днем...
****

Даже живя на краю света, можно писать интересные сообщения, даже просто о жизни. Чем и прославилась среди своих новых
земляков Элеанора Лорд Прей.

Проект EleanorLordPray - это веб-форум, написанный на python. Кроме обычного форумного общения он позволяет обмениваться сообщениями 
сервер-сервер и сервер-пользователь (через многочисленные клиенты).

****
«Вряд ли кто-то любит это неухоженное место так, как я. Все смеются надо мной, а я ничего не могу с собой поделать. Одна только мысль, 
что можно жить где-то, где я не буду видеть эту голубую бухту и два залива, приводит меня в ужас». Это строки 
из письма американки Элеоноры Прей, переехавшей на Дальний Восток с мужем бизнесменом. 
****

Как средство общения, ELP имеет несколько представлений:

*Форум*

Практически все знают, как выглядит форум. Форум разделён на подфорумы, подфорумы разделены на темы. Если в какой-то теме
появляется ответ, то эта тема становится самой верхней для данного подфорума. Форумы удобны, когда хочется отслеживать 
только конкретные темы, не обращая внимания на все остальные. Или когда хочется побродить по архивам - листать топики удобнее, чем эхи.

Сообщения в конкретной теме идут от старых к новым, в так называемом _естественном_ порядке.

*Блог*

Похоже на форум, но верхнее сообщение темы видно всё, а не только заголовок.
Добавление комментария не изменяет порядок блогов, по-прежнему самая новая тема будет самой верхней.
Сами блоги идут от новой записи к старым, а комментарии внутри тем - от старых комментариев к новым.

*Эха*

Все сообщения отдельного подфорума (эхи) идут без разделения на темы и ответы. Новые сообщения - сверху. Все остальные серверы,
кроме elp, ведут своё общение в эхах, также в виде эх сделано и общение в клиентах.

== Авторизация

Для написания сообщений на форуме требуется авторизация. А где её взять? Даже такая простая вещь, как регистрация на форуме,
в elp превращена в подвиг. Доступ идёт по квиткам, а квитки выдаёт 
_сервер регистрации, авторицазции, визового контроля и вообще, вас здесь не стояло_.
Но на второй взгляд всё не так страшно, как на первый, и сервер выдачи квитков приделывается элементарно. Для веб-юзеров
вообще нет никакой заботы, на каком именно сайте они регистрируются - зато такая плавающая авторизация позволяет иметь
один квиток для всех поддерживающих серверов.


== Клиенты

****
Являясь наблюдательной рассказчицей, все особенности своей жизни на новом месте Элеонора Прей смогла описать подробно и увлекательно. 
Практически ежедневно, а иногда и по нескольку раз в день она отправляла письма своим родственникам и знакомым в США, Китай и страны 
Европы. В итоге накопилось собранное за 36 лет жизни во Владивостоке уникальное эпистолярное наследие — более двух тысяч писем на 16 
тысячах страниц. Получился своеобразный «роман в письмах» о Владивостоке. Или «блог», как сказали бы сейчас.
****

За годы существования ii, idec, гк11 и других наборов букв было написано несколько клиентов, для того, чтобы оставаться на связи
и иметь копии сообщений даже тогда, когда постоянный онлайн недоступен. Иных уж нет, других долечим. Самые интересные из них:

**51talk**: локальный сервис, работающий через браузер (офлайн): http://51t.ru/s/51talk-elp.tar.gz

**Caesium**: Для тех, кто скучает по ГолдЕду: http://git.spline-online.tk/spline/caesium

**idec-mobile**: Клиент для Android http://github.com/vit1-irk/idec-mobile

**idec.el**: клиент для Emacs http://github.com/Difrex/idec.el

Храните свои сообщения в сухом надёжном месте, недоступном для детей.

== Обмен между серверами

NOTE: Хоть ii и был изначально изобретён в этих стенах, но сейчас используется его форк IDEC. Описание формата есть на https://ii-net.tk
      Проект ГК11 более никак не относится к этому формату и никак не развивает, а просто использует, поэтому описание смотрите на его
      официальном сайте.

Итак, вы захотели открыть свой форум. Вдохновились прочитанным выше, и решили выбрать в качестве серверного приложения EleanorLordPray.

Но что делать, если вы форум открыли, а сообщений всё нет и нет?

На помощь придёт ii/idec (или, для краткости гк11). Чтобы не скучать в одиночку, станции ii/idec/гк11 (ничё так сократил) 
обмениваются трафиком. Если вы создаёте свой форум, но есть интересующие вас эхи на других, вы подписываетесь на эти эхи, 
убеждаетесь, что всё нормально, а потом договариваетесь с той станцией, готова ли она принимать вас вместе с вашими безумными пойнтами.

Таким нехитрым способом вы можете создать у себя иллюзию активного форума.

Сводка эх есть на мета-трекере http://meta.gk11.ru/

****
4 июля 2014 года американке Элеоноре Лорд Прей поставили во Владивостоке памятник — недалеко от того дома, где она прожила 36 лет. Она стоит у почтамта на Светланской улице, на ступеньках, ведущих к Почтовому переулку, и прижимает к груди очередное письмо из Владивостока.
****

Пишите письма! С творческим приветом, проект ГК11 и EleanorLordPray, http://gk11.ru
